include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    eol_at_end_of_file: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    - build/**
linter:
  rules:
    file_names: false
